// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUxxRzhwXMsjw2wrj-mVs_ik6Y13sYszk',
    appId: '1:357597880680:android:f694781f72b873d1a936dd',
    messagingSenderId: '357597880680',
    projectId: 'test-login-90055',
    storageBucket: 'test-login-90055.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUxxRzhwXMsjw2wrj-mVs_ik6Y13sYszk',
    appId: '1:357597880680:android:f694781f72b873d1a936dd',
    messagingSenderId: '357597880680',
    projectId: 'test-login-90055',
    storageBucket: 'test-login-90055.firebasestorage.app',
    iosBundleId: 'com.sritranggroup.stlconnect',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUxxRzhwXMsjw2wrj-mVs_ik6Y13sYszk',
    appId: '1:357597880680:android:f694781f72b873d1a936dd',
    messagingSenderId: '357597880680',
    projectId: 'test-login-90055',
    authDomain: 'test-login-90055.firebaseapp.com',
    storageBucket: 'test-login-90055.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUxxRzhwXMsjw2wrj-mVs_ik6Y13sYszk',
    appId: '1:357597880680:android:f694781f72b873d1a936dd',
    messagingSenderId: '357597880680',
    projectId: 'test-login-90055',
    storageBucket: 'test-login-90055.firebasestorage.app',
    iosBundleId: 'com.sritranggroup.stlconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUxxRzhwXMsjw2wrj-mVs_ik6Y13sYszk',
    appId: '1:357597880680:android:f694781f72b873d1a936dd',
    messagingSenderId: '357597880680',
    projectId: 'test-login-90055',
    authDomain: 'test-login-90055.firebaseapp.com',
    storageBucket: 'test-login-90055.firebasestorage.app',
  );

}